//! Addressing of NetherNet networks and connections.

use std::fmt;
use webrtc::ice_transport::ice_candidate::RTCIceCandidate;

/// The address of a NetherNet network, optionally referencing a single connection
/// within it.
///
/// Connection IDs are generated by the connecting side and are only unique within
/// the network they were signaled to, so both IDs are needed to reference a connection.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Addr {
    /// Unique ID of the NetherNet network.
    pub network_id: String,

    /// Unique ID of the connection, or zero when the address refers to the network itself.
    pub connection_id: u64,

    /// ICE candidates gathered locally or signaled by the remote connection.
    pub candidates: Vec<RTCIceCandidate>,

    /// Candidate selected by the ICE transport, if it has selected a pair yet.
    pub selected_candidate: Option<RTCIceCandidate>,
}

impl Addr {
    /// Creates an address for a connection within the network.
    pub fn new(network_id: String, connection_id: u64) -> Self {
        Self {
            network_id,
            connection_id,
            candidates: Vec::new(),
            selected_candidate: None,
        }
    }

    /// Creates an address referencing a network rather than a single connection.
    pub fn network(network_id: String) -> Self {
        Self::new(network_id, 0)
    }
}

impl fmt::Display for Addr {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.network_id)?;
        if self.connection_id != 0 {
            write!(f, " ({})", self.connection_id)?;
        }
        if let Some(candidate) = &self.selected_candidate {
            write!(f, " ({})", candidate)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn network_address_omits_connection_id() {
        assert_eq!(Addr::network("1234".to_string()).to_string(), "1234");
    }

    #[test]
    fn connection_address_includes_connection_id() {
        assert_eq!(Addr::new("1234".to_string(), 42).to_string(), "1234 (42)");
    }
}
